config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'site#home'

  resources :projects, only: [:index, :show, :new, :create] do
    resources :time_entries, except: [:show]
  end

  get '/contact', to: 'site#contact'

  get '/say_name/:name', to: 'site#say_name'

  get '/calculator' => 'site#calculator'

  post '/calculate' => 'site#calculate'

end

app/models/project.rb
class Project < ActiveRecord::Base
	# set_table_name 'projects' #this is not neccessairy, because rails will
							#automatically create a table with this name
	has_many :time_entries
	validates :name, presence: true, 
	uniqueness: true, 
	length: { maximum: 30 }, 
	format: { with: /\s[a-zA-Z0-9]/}

	def self.clean_old
		old_projects = Project.where("created_at < ?", 7.days.ago)
		old_projects.destroy_all
	end
end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
	belongs_to :project
	validates :hours, presence: true
	validates :minutes, presence: true
	validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.order(created_at: :desc).limit(10)
		render 'index'
	end
	def new
		@my_project = Project.new
		render "new"
	end
	def create
		@my_project = Project.new(
			:name => params[:project][:name],
			:description => params[:project][:description])
		@my_project.save
		redirect_to "/projects/#{@my_project.id}"
	end
	def show
		@my_project = Project.find_by(id:params[:id])
		unless @my_project
			render "no_projects_found"
		end
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		render 'home' #name of views template. if the name of views template is the same of 
					  #the method, you don't need this line
	end
	def contact
		render 'contact'
	end
	def say_name
		@name = params[:name]
		render 'say_name'
	end
	def calculator
		render 'calculator'
	end
	def calculate
		@num1 = params[:first_num].to_f
		@num2 = params[:second_num].to_f
		@result = @num1 + @num2
		render 'calculate'
	end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	def index
		@my_project = Project.find(params[:project_id])
		@my_entries = @my_project.time_entries
	end
	def new
		@my_project = Project.find_by(id: params[:project_id])
		@my_entry = @my_project.time_entries.new
		render "new"
	end
	def create
		@my_project = Project.find params[:project_id]
		@my_entry = @my_project.time_entries.new(
			hours: params[:time_entry][:hours],
			minutes: params[:time_entry][:minutes],
			date: params[:time_entry][:date]
			)
		if @my_entry.save
			redirect_to action: "index", controller: "time_entries", 
			project_id: @my_project.id
		else
			render "new"
		end
	end
	def edit
		@my_project = Project.find params[:project_id]
		@my_entry = @my_project.time_entries.find params[:id]
	end
	def update
		@my_project = Project.find_by(id: params[:project_id])
		@my_entry = @my_project.time_entries.find_by(id: params[:id])

		if @my_entry.update(entry_params)
			redirect_to action: "index", controller: "time_entries", 
			project_id: @my_project.id
		else
			render "edit"
		end
	end
	def destroy
		@my_project = Project.find params[:project_id]
		@my_entry = @my_project.time_entries.find_by(id: params[:id])
		@my_entry.destroy
		redirect_to action: "index", controller: "time_entries", 
			project_id: @my_project.id
	end
	private
	def entry_params
		params.require(:time_entry).permit(:hours, :minutes, :date)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>  <!-- pulls the content from the other pages and throws in this format -->
			  <!-- if there's a content that is common to all pages (for ex: footer) -->
			  <!-- it would be better to insert it here -->

</body>
</html>

app/views/partials/_registration.html.erb
<h3>Sign up now!</h3>

app/views/projects/edit.html.erb
<%= form_for [@my_project, @my_entry] do |f| %>
	<%= f.label :hours %>
	<%= f.number_field :hours %>

	<%= f.label :minutes %>
	<%= f.number_field :minutes %>

	<%= f.label :date %>
	<%= f.date_field :date %>

	<%= f.submit "Save" %>
	<%= link_to 'Cancel', project_time_entries_path(@my_project) %>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul>
	<% @projects.each do |project| %>
		<li>
			<b><%= link_to project.name, "/projects/#{project.id}" %></b>
			<% if (project.description) %>
				-
			<% end %>
			<%= project.description %>
		</li>
	<% end %>
</ul>

<%= link_to "Create a new project", new_project_path %>

app/views/projects/new.html.erb
<h1>Add a Project</h1>
<%=  form_for @my_project do |f| %>
	<%= f.label :name %>
	<%=f.text_field :name %>
	<br><br>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<br><br>
	<%= f.button %>
<% end %>

app/views/projects/show.html.erb
<h3><%= @my_project.name %></h3>
<p><%= @my_project.description %></p>
<% @my_project.time_entries.each do |time_entry| %>
	<b><p>Entry: </p></b>
	<p>Hours: <%= time_entry.hours%> Minutes: <%= time_entry.minutes%></p>
<% end %>
<br>
<%= link_to 'Return to projects\'s page', projects_path %>

app/views/site/calculate.html.erb
The result of <%= @num1 %> + <%= @num2 %> is <%= @result %>

app/views/site/calculator.html.erb
<form action="/calculate" method="POST">
	<input type="text" name="first_num" placeholder="First Number">
	<input type="text" name="second_num" placeholder="Second Number">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<button type="submit">Add</button>
</form>

app/views/site/contact.html.erb
<p>contact@example.com</p>

app/views/site/home.html.erb
<h1>Time Tracking</h1>

<%= render "partials/registration" %>

<!-- <img src="/assets/dramatic-glasses.gif" alt="Kid removing his sunglasses  epically"> -->
<%= image_tag "dramatic-glasses.gif", :alt => "boy taking glasses off" %>

app/views/site/say_name.html.erb
<h1>Hello <%= @name %></h1>

app/views/time_entries/_form.html.erb
<% if @my_entry.errors.any? %>
	<% if flash[:error] %>
		<% flash[:error] %>
	<% end %>
	<ul>
		<% @my_entry.errors.full_messages.each do |error_msg| %>
			<li><%=error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@my_project, @my_entry] do |f| %>
		<%= f.label :hours %>
		<%= f.number_field :hours %>

		<%= f.label :minutes %>
		<%= f.number_field :minutes %>

		<%= f.label :date %>
		<%= f.date_field :date %>

		<%= f.submit "Save" %>
		<%= link_to("Cancel", project_time_entries_path) %>
<% end %>

app/views/time_entries/edit.html.erb
<%= render "form" %>

app/views/time_entries/index.html.erb
<h1><%= @my_project.name %></h1>
<ul>
	<% @my_entries.each do |entry| %>
		<li>
			<%= entry.hours %> h
			<%= entry.minutes %> m -
			<%= entry.date %>
			<%= link_to "Edit time entry", edit_project_time_entry_path(entry.project_id, entry.id)  %>
			<%= link_to("Delete this entry", project_time_entry_path(entry.project_id, entry.id), method: "delete", data: { confirm: "Are you sure?"}) %>
			<!-- entry.project_id (this only works in the loop) = @my_project.id = @my_project -->
			<!-- entry.id = entry (only for path purposes) -->
		</li>
	<% end %>
</ul>

<%= link_to "Add a new time entry", new_project_time_entry_path(@my_project.id)  %>

app/views/time_entries/new.html.erb
<h2>Add a Time Entry</h2>

<%= render "form" %>